[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_tutorial = "817ZDyafNmREXLmFD5sQprc3DAhW55BMHKA8x4ZinnHC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bugra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
